# Generated by Django 5.2 on 2025-04-04 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Tecnoempleo, InfoJobs, LinkedIn', max_length=100, unique=True, verbose_name='Nombre de la Fuente')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL Principal')),
                ('last_scraped', models.DateTimeField(blank=True, null=True, verbose_name='Última Extracción')),
            ],
            options={
                'verbose_name': 'Fuente de Empleo',
                'verbose_name_plural': 'Fuentes de Empleo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Fecha del Análisis')),
                ('period', models.CharField(help_text='Ej: Mensual, Trimestral, Últimos 6 meses', max_length=50, verbose_name='Periodo Analizado')),
                ('region', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Región')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Industria/Sector')),
                ('skill_trends', models.JSONField(verbose_name='Tendencias de Habilidades')),
                ('source_description', models.CharField(blank=True, help_text="Describe los datos usados, ej: 'InfoJobs + Tecnoempleo'", max_length=255, verbose_name='Fuente de los Datos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tendencia de Mercado',
                'verbose_name_plural': 'Tendencias de Mercado',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Título del Puesto')),
                ('company', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la Oferta')),
                ('salary_range', models.CharField(blank=True, help_text='Ej: 25000-35000 EUR Anual, No especificado', max_length=150, null=True, verbose_name='Rango Salarial')),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Publicación')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL Original')),
                ('applicants_count', models.IntegerField(blank=True, help_text='Si la fuente proporciona esta información.', null=True, verbose_name='Número de Inscritos')),
                ('raw_data', models.JSONField(blank=True, help_text='Datos originales obtenidos del scraping o API.', null=True, verbose_name='Datos Crudos (JSON)')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Extracción/Integración')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización (en BD)')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la oferta aún se considera vigente.', verbose_name='¿Oferta Activa?')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='job_offers', to='users.skill', verbose_name='Habilidades Requeridas')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offers', to='market_analysis.jobsource', verbose_name='Fuente')),
            ],
            options={
                'verbose_name': 'Oferta de Empleo',
                'verbose_name_plural': 'Ofertas de Empleo',
                'ordering': ['-publication_date', '-scraped_at'],
                'indexes': [models.Index(fields=['-publication_date', '-scraped_at'], name='market_anal_publica_231d39_idx'), models.Index(fields=['location', 'company'], name='market_anal_locatio_1e2cf8_idx')],
            },
        ),
    ]
