# Generated by Django 5.2 on 2025-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Ej: 25000-35000 EUR Anual, No especificado', max_length=255, null=True, verbose_name='Rango Salarial'),
        ),
    ]
