# Generated by Django 5.2 on 2025-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0002_alter_joboffer_company_alter_joboffer_location_and_more'),
        ('users', '0002_alter_userprofile_options_role_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='joboffer',
            name='market_anal_locatio_1e2cf8_idx',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='industry',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: Tecnología, Finanzas, Salud', max_length=100, null=True, verbose_name='Industria/Sector'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['location', 'company', 'industry'], name='market_anal_locatio_53c46e_idx'),
        ),
    ]
